### PR TITLE
Remove references to deprecated CTCarrier

### PR DESCRIPTION
**Pull request by samedson**
https://developer.apple.com/forums/thread/714876
 - Deprecated with no replacement in iOS 16.4.

Depends on: https://github.com/firebase/firebase-ios-sdk/pull/11144

Currently FirebaseSessions is the only user of this API. 

TODO
- [x] Run tests
- [x] Submit https://github.com/firebase/firebase-ios-sdk/pull/11144
- [ ] Wait until the next major GoogleUtilities release

### CODE REVIEW

**Review by paulb777 — COMMENTED** [review]
I believe this change needs to wait until the next GoogleUtilities major release to avoid breaking existing installs depending on GoogleUtilities 7.x

**Comment by paulb777** [comment]
Added to the 8.0.0 milestone

**Comment by ncooke3** [comment]
Hi @samedson, I changed the base branch to merge into `release-8.0` as we are now working on prepping for GUls v8. Is this PR ready for a final review?

**Comment by samedson** [comment]
@ncooke3 yes it is!

**Review by ncooke3 — APPROVED** [review]
nice cleanup!

**Pull request merged**
